[대상 문자열]
txt = ‘파이썬오늘은\t문자열을\t배웠고,\t그\t지식을\t이용해서\t문자열\t수정을\t해\t봅시다.\n파이썬’

1. 모든 한글만 추출한다
2. 콤마(,)를 기준으로 줄바꿈을 해 문자열을 출력한다
3. ‘파이썬’ 이라는 글자를 지워 txt3 변수에 저장한다
4. 출력 예시와 같이 출력한다

[출력 예시]
 오늘은% 문자열을% 배웠고,% 
 그% 지식을% 이용해서% 문자열% 수정을% 해% 봅시다.
 
 ppt 3장 끝 과제


In [1]:
txt = '파이썬오늘은\t문자열을\t배웠고,\t그\t지식을\t이용해서\t문자열\t수정을\t해\t봅시다.\n파이썬'

In [2]:
import re

In [3]:
re.sub('[^가-힣]','',txt)

'파이썬오늘은문자열을배웠고그지식을이용해서문자열수정을해봅시다파이썬'

In [4]:
print(txt.replace('.','\n'))

파이썬오늘은	문자열을	배웠고,	그	지식을	이용해서	문자열	수정을	해	봅시다

파이썬


In [5]:
txt3 = txt.replace('파이썬','')

In [6]:
txt3

'오늘은\t문자열을\t배웠고,\t그\t지식을\t이용해서\t문자열\t수정을\t해\t봅시다.\n'

In [7]:
print(txt3.replace('그','\n그').replace('\t','% '))

오늘은% 문자열을% 배웠고,% 
그% 지식을% 이용해서% 문자열% 수정을% 해% 봅시다.



복습 0513일

0.1 0.2 0.3 0.4 0.5

In [8]:
for i in range(1,6,1):
    print(i/10)

0.1
0.2
0.3
0.4
0.5


넘파이의 연산

In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr + 15

array([16, 17, 18, 19, 20])

In [13]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [14]:
#arr + np.array([1,2])

In [15]:
np.append(arr, [1,2,3])   # 

array([1, 2, 3, 4, 5, 1, 2, 3])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr[4]

5

In [18]:
arr[-3]

3

In [19]:
arr[1:]   # 1빼고

array([2, 3, 4, 5])

In [20]:
arr[2::2]

array([3, 5])

In [21]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2d + 1        # 브로드캐스팅 가능

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [24]:
arr2d[1] * 2

array([ 8, 10, 12])

In [25]:
np.savez('./arr.npz', AAA=arr2d)

In [26]:
np.load('./arr.npz')['AAA']     # 파일명 쓸때는 자동완성 TAP 키 쓰기.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

판다스의 연산

In [27]:
import pandas as pd

In [28]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [29]:
np.array([1,2,3])

array([1, 2, 3])

In [30]:
df = pd.DataFrame([[1,2,3],[4,5,6]], columns=['A','B','C'], index=['가','나'])#.T         # .T 추가시 = Transform 명령어 컬럼과 로우가 바뀐다. 축정보가 바뀐다.

In [31]:
df

A  B  C
가  1  2  3
나  4  5  6

In [32]:
df['B']['나']      # 인덱싱 할때 [row] [colunm] 반대로 해야됨

5

In [33]:
df.loc['나','B']   # 인덱스이 값으로

5

In [34]:
df.iloc[1,1]   # 인덱스이 순서로

5

In [35]:
df + 1   # 브로드캐스팅 가능

A  B  C
가  2  3  4
나  5  6  7

In [36]:
df['A'] = [[1,2],3.7]

In [37]:
df

A  B  C
가  [1, 2]  2  3
나     3.7  5  6

In [38]:
df * 4

A   B   C
가  [1, 2, 1, 2, 1, 2, 1, 2]   8  12
나                      14.8  20  24

In [39]:
df.to_excel('./df.xlsx')   # ,index=False, header=None)

In [40]:
pd.read_excel('./df.xlsx', index_col=0, comment='#', thousands='.')#header=1)     # header = row 이름 , index = coulunm 이름

A  B  C
가  [1, 2]  2  3
나     3.7  5  6

In [41]:
df.to_csv('./df.csv', encoding='cp949')   # 한글 적어야되면 encoding='cp949' 추가한다.

In [42]:
try:
    pd.read_csv('./df.csv', index_col=0)    # index_col=0 > 0,0배열에 none값으로 설정됨.
except UnicodeDecodeError:
    pd.read_csv('./df.csv', encoding='cp949', index_col=0)        # 에러의 예외처리 사용 방법 try ~ except

In [43]:
df['D'] = [1,2]     # Pandas는 없는것도 추가할수 있다.

In [44]:
df

A  B  C  D
가  [1, 2]  2  3  1
나     3.7  5  6  2

In [45]:
pd.concat([df,pd.DataFrame([[1,2,3,4]], columns=['A','B','C','D'], index=['다'])])

A  B  C  D
가  [1, 2]  2  3  1
나     3.7  5  6  2
다       1  2  3  4

In [46]:
df

A  B  C  D
가  [1, 2]  2  3  1
나     3.7  5  6  2

In [47]:
pd.concat([df,pd.DataFrame([3,4,5], columns=['X'], index=['가','나','다'])], axis=1)
# 종속적으로 컬럼 추가하는 방법

A    B    C    D  X
가  [1, 2]  2.0  3.0  1.0  3
나     3.7  5.0  6.0  2.0  4
다     NaN  NaN  NaN  NaN  5

In [48]:
df

A  B  C  D
가  [1, 2]  2  3  1
나     3.7  5  6  2

In [49]:
df.loc[['가','나'],['B','C']]      # 판다스에서 여러개 집어 넣는건 인덱싱으로 가능하다.

B  C
가  2  3
나  5  6

In [50]:
df.loc[:,'B':'D']     # : (콜론만찍으면) 처음부터 끝까지 .. 인덱싱 -1까지 처리 안한다

B  C  D
가  2  3  1
나  5  6  2

In [51]:
df.iloc[:,1:3]        #  : 처음부터 끝까지 

B  C
가  2  3
나  5  6

df.iloc[:,1:]

In [52]:
na = float('nan')     # 결측시 not available number

In [53]:
na + 100

nan

In [54]:
na - 90

nan

In [55]:
na * 7

nan

In [56]:
na / 8               # 결측시는 어떤연산을 return 하더라도 nan 값이 나온다.

nan

In [57]:
na > 7

False

In [58]:
na < 7

False

In [59]:
na == 7

False

In [60]:
na != 7               # nan값은 산술연산은 모두 nan 논리연산은 !=를 제외하고 모두 False가 나온다.

True

In [61]:
7 == 7

True

In [62]:
7 != 7

False

In [63]:
na == na

False

In [64]:
na != na

True

ll = [1,2,3,4,na,5,6,7,na,8,9] 

nan값이 몇번째 나오는지 확인하는 프로그램을 만들어라.

In [65]:
ll = [1,2,3,4,na,5,6,7,na,8,9]

In [66]:
ll

[1, 2, 3, 4, nan, 5, 6, 7, nan, 8, 9]

In [67]:
for idx, val in enumerate(ll):
    print(idx, val)

0 1
1 2
2 3
3 4
4 nan
5 5
6 6
7 7
8 nan
9 8
10 9


In [68]:
for idx, val in enumerate(ll):      # 7 == 7 True na == na False
    if val != val:
        print(idx)
    #else:
     #   print(idx)

4
8


In [69]:
print(val[4])

TypeError: 'int' object is not subscriptable

In [ ]:
df = pd.DataFrame(ll)

In [ ]:
df != df

In [ ]:
df.isna()   # 열별 (컬럼별) NA 개수 확인 

In [ ]:
m = df.isna().values

In [ ]:
df[m]

true false기반 인덱싱

In [ ]:
df_2d = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
m = df_2d[2] >= 6

In [ ]:
df_2d[2][m]             # m = masking -는 not 과 같다.

In [ ]:
m

In [ ]:
df_2d.drop(2, axis=1)# .drop(2, axis=1) 0번부터시작 2번째열 삭제
                      #, inplace=True) or df_2d = 값에 저장 하면 저장이된다                     

In [ ]:
df_2d                               # drop과같이 결과가 return이 되는 경우는 저장이 안된다

In [ ]:
arr = np.array([1,2,3,6,54,7,8,5,2,1,4])

In [ ]:
arr

In [ ]:
m = arr > 5

In [ ]:
arr[m]                # nan파일도 indexing이 된다.      # arr에 m를 인덱싱

In [ ]:
[1,2,3,6,54,7,8,5,2,1,4][m] # list는 masking이 안된다

In [70]:
import pandas as pd

In [71]:
loan = pd.read_excel('../../Downloads/BestLoanList.xlsx')

In [72]:
seller = pd.read_excel('../../Downloads/BestSellerList.xlsx')

In [ ]:
seller.columns = ['월','순위','서명','저자','출판사','출판년도','정가','적립포인트','대분야','ISBN']

In [ ]:
seller.tail(1)

In [ ]:
loan.head(1)

In [ ]:
pd.merge(seller, loan, left_on='ISBN', right_on='ISBN', how='inner')     # inner 양쪽에 같은 isbn이 있는경우만 select

In [ ]:
data = {'A': [1,2,3,4,5],'B': ['hello','python','hi','jupyter','py']}
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
df[df['A'] <= 3] # masking 사용한방법       slice 으로도 된다.

In [ ]:
m1 = df['A'] <= 4            # masking 방법
df2 = df[m1]

In [ ]:
m2 = df2['A'] >= 3
df2[m2]

In [ ]:
df.query('3 <= A <= 4')          # query() 함수 사용 방법

In [ ]:
df[df['B'] == 'hi']

In [ ]:
df.query('B == "hi"')

In [ ]:
s = 'hi'

In [ ]:
df[df['B'] == s]

In [ ]:
df.query('B == @s')                       # @s < 변수만 가능 문자열은 안됨.

format 방법 1 2 3

In [ ]:
s = 'hi~'
q = 123.789
o = {123,456}

In [ ]:
f'변수의 할당된 값은 {s},{q},{o} 입니다'

In [ ]:
'변수의 할당된 값은 각각 {},{},{} 입니다'.format(s, q, o)

In [ ]:
'변수의 할당된 값은 각각 %s,%10.2f,%s 입니다' %(s,q,o)               # %s가 문자기반으로 들어갑니다 / 문자기반의 문자열이 들어간 방법

In [ ]:
's의 값은', s ,'입니다'               # 한 문자열로 처리가 안된다

In [ ]:
's의 값은' + s + '입니다'            # 숫자랑 문자가 덧셈이 안된다. 띄어쓰기 안됨

In [ ]:
'20'.zfill(5)            # zfill = zerofill

In [ ]:
seller

In [ ]:
seller['할인가'] = seller['정가'] * 0.9

In [ ]:
seller

In [ ]:
seller['정가'].apply(lambda x: x*0.9)        # lambda x : x값을 받는 함수입니다.

In [ ]:
[s*0.9 for s in seller['정가']]

In [ ]:
for s in seller['정가']:
    print(s*0.9)

In [ ]:
seller[seller['정가'] == 18000].index                  # [마스킹]

In [ ]:
m = seller['서명'].str.contains('역사')            # contains 포함하는함수 사용

In [ ]:
seller.loc[m, '서명']

In [ ]:
b = seller[seller['대분야'].str.contains('소설')] #총222

In [ ]:
p = seller[seller['정가'] <= 15000]  #총518

In [ ]:
y = seller[seller['출판년도'] >= 20200101] #총947
#seller[seller['2010 >= '출판년도' >= 2018']
#seller['출판년도'] > 2020

In [ ]:
result = pd.concat([b,p,y]) # 마스킹한 3개의 객체 각 3가지 조건 행을 더한다. 총1687열

In [ ]:
result1 = result.loc[[0], :]            # 전체 중에 행이 제일 위쪽 순위가 높은 부분만 추출
#result.iloc(min(result['순위']))

In [ ]:
result1.duplicated(subset=None,keep='first')

In [ ]:
result1.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

In [ ]:
result1.d

In [73]:
seller.head(1)

월  순위                   도서명   저자    출판사     출판 일자     정가  적립포인트    대분야  \
0  2021년   1  달러구트 꿈 백화점(레인보우 에디션)  이미예  팩토리나인  20200708  13800    690  판타지소설   

            ISBN  
0  9791165341909

In [74]:
temp = seller.query('대분야.str.contains("소설") and 정가 <= 15000') # and 출판_일자 >= 20200101')

In [76]:
temp[temp['출판 일자'] >= 20200101].sort_values('순위', ascending=True)                 # masking

월   순위                      도서명       저자              출판사     출판 일자  \
0    2021년    1     달러구트 꿈 백화점(레인보우 에디션)      이미예            팩토리나인  20200708   
500     5월    1                     작별인사      김영하             복복서가  20220502   
300     3월    1  불편한 편의점(40만부 기념 벚꽃 에디션)      김호연            나무옆의자  20210420   
200     2월    1  불편한 편의점(40만부 기념 벚꽃 에디션)      김호연            나무옆의자  20210420   
801     8월    2        불편한 편의점 2(단풍 에디션)      김호연            나무옆의자  20220810   
..     ...  ...                      ...      ...              ...       ...   
594     5월   95         수상한 중고상점(눈꽃 에디션)  미치오 슈스케                놀  20220412   
995     9월   96        칵테일, 러브, 좀비 (리커버)      조예은             안전가옥  20200413   
196     1월   97              소마(리커버 양장본)      채사장  웨일북(whalebooks)  20211224   
798     7월   99                 지구 끝의 온실      김초엽           자이언트북스  20210818   
799     7월  100   여기는 커스터드, 특별한 도시락을 팝니다     가토 겐        필름(Feelm)  20220715   

        정가  적립포인트      대분야           ISBN  
0    13800    690    판타지소설  9791165341909  
500  14000    700   한국소설일반  9791191114225  
300  14000    700   한국소설일반  9791161571188  
200  14000    700   한국소설일반  9791161571188  
801  14000    700   한국소설일반  9791161571379  
..     ...    ...      ...            ...  
594  15000    750   일본소설일반  9791130689241  
995  10000    500  공포/호러소설  9791190174756  
196  15000    750   한국소설일반  9791192097060  
798  15000    750   한국소설일반  9791191824001  
799  15000    750   일본소설일반  9791192403076  

[136 rows x 10 columns]

In [ ]:
seller

In [ ]:
loan